import { useNavigate } from 'react-router-dom'

export default function Features() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-[#080c14] text-[#e8edf5] font-sans overflow-x-hidden">

      {/* Grid background */}
      <div className="fixed inset-0 z-0 pointer-events-none"
        style={{
          backgroundImage: 'linear-gradient(rgba(99,179,237,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(99,179,237,0.04) 1px, transparent 1px)',
          backgroundSize: '48px 48px'
        }}
      />

      {/* Nav */}
      <nav className="relative z-10 flex items-center justify-between px-12 py-5 border-b border-white/5">
        <div className="font-mono text-xl font-bold cursor-pointer" onClick={() => navigate('/')}>
          SAT<span className="text-blue-500">sec</span>
        </div>
        <div className="hidden md:flex gap-8">
          <span onClick={() => navigate('/features')} className="text-sm text-blue-400 cursor-pointer">Features</span>
          <span onClick={() => navigate('/dashboard')} className="text-sm text-[#8899aa] hover:text-[#e8edf5] transition-colors cursor-pointer">Dashboard</span>
          <span className="text-sm text-[#8899aa] hover:text-[#e8edf5] transition-colors cursor-pointer">Pricing</span>
          <span className="text-sm text-[#8899aa] hover:text-[#e8edf5] transition-colors cursor-pointer">Docs</span>
        </div>
        <button onClick={() => navigate('/')} className="bg-blue-500 hover:bg-blue-600 text-white text-sm font-medium px-5 py-2 rounded-lg transition-colors">
          Run Audit
        </button>
      </nav>

      <div className="relative z-10 max-w-4xl mx-auto px-6 py-20">

        {/* Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 bg-blue-500/10 border border-blue-500/30 rounded-full px-4 py-1.5 text-xs text-blue-300 font-mono mb-6">
            <span className="w-1.5 h-1.5 rounded-full bg-blue-500 animate-pulse" />
            Everything you need to monitor your site
          </div>
          <h1 className="text-4xl md:text-5xl font-semibold tracking-tighter text-[#f0f4fa] mb-4">
            Built for agencies.<br />
            <span className="text-blue-500">Loved by developers.</span>
          </h1>
          <p className="text-lg text-[#7a8fa8] font-light max-w-xl mx-auto">
            SATsec automates everything your team does manually — and does it better, faster, and 24/7.
          </p>
        </div>

        {/* Main features */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          {[
            {
              icon: '⚡',
              title: 'Instant Audits',
              desc: 'Paste any URL and get a full 4-dimension report in seconds. Performance, SEO, Accessibility and Security — all in one scan.',
              tags: ['Lighthouse', 'axe-core', 'BeautifulSoup'],
            },
            {
              icon: '🕐',
              title: 'Scheduled Monitoring',
              desc: 'Set it and forget it. Choose every 6 hours, daily, or weekly. SATsec runs automatically on your schedule without anyone touching it.',
              tags: ['Every 6hrs', 'Daily', 'Weekly'],
            },
            {
              icon: '🔔',
              title: 'Smart Alerts',
              desc: 'Get emailed the moment a score drops below your threshold — with a plain-English explanation of exactly what changed and why.',
              tags: ['Email alerts', 'Custom threshold', 'Instant'],
            },
            {
              icon: '📈',
              title: 'Trend Dashboard',
              desc: 'Every audit result is stored with a timestamp. See score trends over time and pinpoint exactly when a deploy broke your site.',
              tags: ['Score history', 'Deploy detection', 'Charts'],
            },
            {
              icon: '⚖️',
              title: 'ADA Compliance',
              desc: 'WCAG AA checks via axe-core — the same standard used in legal proceedings. Know your risk before the lawyer calls.',
              tags: ['WCAG AA', 'axe-core', 'Legal standard'],
            },
            {
              icon: '🤖',
              title: 'AI Summaries',
              desc: 'Every report ends with a plain-English paragraph generated by Claude. Written for clients and executives, not developers.',
              tags: ['Claude AI', 'Plain English', 'Client ready'],
            },
          ].map(({ icon, title, desc, tags }) => (
            <div key={title} className="bg-white/[0.025] border border-white/[0.06] rounded-2xl p-6 hover:border-blue-500/20 transition-colors">
              <div className="w-10 h-10 rounded-xl bg-blue-500/10 flex items-center justify-center text-xl mb-4">{icon}</div>
              <h3 className="text-base font-medium text-[#c8d8e8] mb-2">{title}</h3>
              <p className="text-sm text-[#5a7080] leading-relaxed mb-4">{desc}</p>
              <div className="flex gap-2 flex-wrap">
                {tags.map(tag => (
                  <span key={tag} className="text-xs bg-white/[0.04] border border-white/[0.08] text-[#6a8099] px-3 py-1 rounded-full font-mono">
                    {tag}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Coming soon */}
        <div className="bg-white/[0.025] border border-white/[0.06] rounded-2xl p-6 mb-10">
          <p className="text-xs font-mono text-[#8899aa] uppercase tracking-widest mb-4">Coming Soon</p>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {[
              { icon: '🔍', title: 'Multi-page Crawling' },
              { icon: '🏆', title: 'Competitor Benchmarking' },
              { icon: '📄', title: 'ADA PDF Reports' },
              { icon: '💬', title: 'Slack Integration' },
              { icon: '🔀', title: 'Deploy Diff Detection' },
              { icon: '🌐', title: 'Chrome Extension' },
            ].map(({ icon, title }) => (
              <div key={title} className="flex items-center gap-3 bg-white/[0.02] border border-white/[0.04] rounded-xl px-4 py-3">
                <span className="text-base">{icon}</span>
                <span className="text-sm text-[#4a6070]">{title}</span>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="bg-blue-500/[0.06] border border-blue-500/20 rounded-2xl p-8 text-center">
          <h3 className="text-xl font-medium text-[#e8edf5] mb-2">Ready to put your site under surveillance?</h3>
          <p className="text-sm text-[#4a6070] mb-6">No signup required. Paste a URL and get results in seconds.</p>
          <button onClick={() => navigate('/')} className="bg-blue-500 hover:bg-blue-600 text-white text-sm font-medium px-8 py-3 rounded-lg transition-colors">
            Run Your First Audit →
          </button>
        </div>
      </div>
    </div>
  )
}